language: go
go:
  - "1.10"

addons:
  postgresql: "9.3"

services:
  - postgresql

before_script:
  - sudo -H pip install awscli

install:
  - go get github.com/mitchellh/gox
  - go get github.com/kardianos/govendor
  - govendor sync

script:
  - govendor test +local -cover -v

after_success:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - 'if [ "$BRANCH" == "main" ]; then
    ./scripts/build.sh;
    ./scripts/upload.sh;
    fi'
